disks:
  - name: data
    mountPath: /var/data
    sizeGB: 1
services:
  - type: web
    name: web3-music-backend
    env: node
    plan: starter
    rootDir: backend
    buildCommand: "yarn install && yarn build"
    startCommand: "yarn start"
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 18.17.1
    disk:
      name: data
      mountPath: /var/data
