services:
  - type: web
    name: web3-music-backend
    env: node
    plan: starter
    rootDir: backend
    buildCommand: "yarn install && yarn build"
    startCommand: "yarn start"
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 18.17.1
      - key: RENDER_DISK_MOUNT_PATH
        value: /var/data
    disk:
      name: data
      mountPath: /var/data
  - type: static_site
    name: web3-music-frontend
    buildCommand: "yarn && yarn build"
    publishDir: "dist"

disks:
  - name: data
    mountPath: /var/data
    sizeGB: 1
