services:
  - type: web
    name: web3-music-backend
    runtime: node
    plan: starter
    rootDir: ./backend
    buildCommand: "yarn install && yarn build"
    startCommand: "yarn start"
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 18.17.1
      - key: DATABASE_URL
        value: "file:/var/data/db.json"
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
  - type: web
    name: web3-music-frontend
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    # The command is now set via ENTRYPOINT in the Dockerfile
    # to force Render to stop using a cached command.
    envVars:
      # Pull all variables (CLIENT_ID, CLIENT_SECRET, COOKIE_SECRET)
      # from the specified group. This is the correct syntax.
      - fromGroup: axep-secrets
      # Non-sensitive values set directly
      - key: OAUTH2_PROXY_PROVIDER
        value: "github"
      - key: OAUTH2_PROXY_UPSTREAMS
        value: "file:///app/#/"
      - key: OAUTH2_PROXY_EMAIL_DOMAINS
        value: "*"
      - key: OAUTH2_PROXY_AUTHENTICATED_EMAILS_FILE
        value: "/site_config/email_list.txt"
      - key: OAUTH2_PROXY_COOKIE_SECURE
        value: "true"
      - key: OAUTH2_PROXY_COOKIE_SAMESITE
        value: "lax"
      - key: OAUTH2_PROXY_SCOPE
        value: "user:email"
 