services:
  # Blueprint for the Axep web3 music platform
  - type: web
    name: web3-music-frontend
    runtime: static
    rootDir: .
    buildFilter:
      paths:
      - "src/**/*.ts"
      - "src/**/*.tsx"
      - "package.json"
    buildCommand: "npm install && npm run build"
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
  - type: web
    name: web3-music-backend
    runtime: node
    plan: free
    rootDir: backend
    buildFilter:
      paths:
        - "src/index.ts"
        - "package.json"
    buildCommand: "npm install && npm run build"
    startCommand: "node dist/index.js"
    envVars:
      - key: NODE_ENV
        value: production
      - fromGroup: pinata-jwt
      - key: RENDER_DISK_MOUNT_PATH
        value: /var/data
    disk:
      name: data-disk
      mountPath: /var/data
      sizeGB: 1 