    services:
      - type: web
        name: web3-music-backend
        env: node
        plan: starter
        rootDir: backend
        buildCommand: "yarn install && yarn build"
        startCommand: "yarn start"
        healthCheckPath: /
        disks:
          - name: data
            mountPath: /var/data
            sizeGB: 1
