services:
  - type: web
    name: web3-music-backend
    runtime: node
    plan: starter
    rootDir: ./backend
    buildCommand: "yarn install && yarn build"
    startCommand: "yarn start"
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 18.17.1
      - key: DATABASE_URL
        value: "file:/var/data/db.json"
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
  - type: static site
    name: axep-frontend
    plan: starter
    buildCommand: "yarn install && yarn build"
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
 