services:
  # Frontend Static Site
  - type: web
    name: axep-frontend
    env: static
    rootDir: ./
    buildFilter:
      paths:
        - "src/**/*"
        - "public/**/*"
        - "package.json"
        - "package-lock.json"
        - "tsconfig.json"
        - "vite.config.ts"
    build_command: "npm install && npm run build"
    static_publish_path: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend Web Service
  - type: web
    name: axep-backend
    env: node
    rootDir: ./backend
    build_command: "npm install && npm run build"
    start_command: "npm start"
    envVars:
      - key: PINATA_JWT
        sync: false
      - key: VITE_BACKEND_URL
        fromService:
          type: web
          name: axep-backend
          property: url 