services:
  # Backend Web Service
  - type: web
    name: axep-backend
    env: node
    rootDir: ./backend
    buildCommand: "npm ci && npm run build"
    startCommand: "npm start"
    healthCheckPath: /health
    envVars:
      - key: PINATA_JWT
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"

  # Frontend Static Site
  - type: web
    name: axep-frontend
    env: static
    rootDir: ./
    buildFilter:
      paths:
        - "src/**/*"
        - "public/**/*"
        - "package.json"
        - "package-lock.json"
        - "tsconfig*.json"
        - "vite.config.ts"
        - "index.html"
      ignoredPaths:
        - "backend/**/*"
        - "contracts/**/*"
        - "scripts/**/*"
        - "test*"
        - "*.md"
    buildCommand: "npm ci && npm run build"
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_BACKEND_URL
        value: https://axep-backend.onrender.com