[build]
builder = "NIXPACKS"
buildCommand = "rm -rf node_modules/.cache && npm install --production && npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"
PORT = "3001" 